======================================================================
FAIL: test_strength_one_to_many_propagate (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_tests/test_device/test_integration.py", line 130, in test_strength_one_to_many_propagate
    self.assertNotEqual(loop, TotalWaitTime-1)
AssertionError: 99 == 99

----------------------------------------------------------------------


[transport] handler: appending defer Defer(callback=<function callback at 0x7fc5bf70e488>, error_cb=<function error_callback at 0x7fc5bf6f8b90>, verify=<function <lambda> at 0x7fc5bf6f8aa0>, allowed_replies=[149, 175], message=Message(destination=3, command=148, payload=[0, 133, 3, 0, 204, 0]), timeout=1417594300458) to queue
[transport] adding to queue: queue_id  0d87c68a56bc8eb803b44f25abb627786
(None, None, None)



